Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 560, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
np.testing.assert_almost_equal(c, 270.15)
print('Test 3 Passed!')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAssertionError[0m                            Traceback (most recent call last)
[0;32m/tmp/ipykernel_1764/3447443753.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mnp[0m[0;34m.[0m[0mtesting[0m[0;34m.[0m[0massert_almost_equal[0m[0;34m([0m[0mc[0m[0;34m,[0m [0;36m270.15[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mprint[0m[0;34m([0m[0;34m'Test 3 Passed!'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/numpy/testing/_private/utils.py[0m in [0;36massert_almost_equal[0;34m(actual, desired, decimal, err_msg, verbose)[0m
[1;32m    597[0m         [0;32mpass[0m[0;34m[0m[0;34m[0m[0m
[1;32m    598[0m     [0;32mif[0m [0mabs[0m[0;34m([0m[0mdesired[0m [0;34m-[0m [0mactual[0m[0;34m)[0m [0;34m>=[0m [0;36m1.5[0m [0;34m*[0m [0;36m10.0[0m[0;34m**[0m[0;34m([0m[0;34m-[0m[0mdecimal[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 599[0;31m         [0;32mraise[0m [0mAssertionError[0m[0;34m([0m[0m_build_err_msg[0m[0;34m([0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    600[0m [0;34m[0m[0m
[1;32m    601[0m [0;34m[0m[0m

[0;31mAssertionError[0m: 
Arrays are not almost equal to 7 decimals
 ACTUAL: 273.15
 DESIRED: 270.15
AssertionError: 
Arrays are not almost equal to 7 decimals
 ACTUAL: 273.15
 DESIRED: 270.15

