Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
np.testing.assert_almost_equal(c, 270.15)
print('Test 3 Passed!')
------------------


[31m---------------------------------------------------------------------------[39m
[31mAssertionError[39m                            Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[5][39m[32m, line 1[39m
[32m----> [39m[32m1[39m [43mnp[49m[43m.[49m[43mtesting[49m[43m.[49m[43massert_almost_equal[49m[43m([49m[43mc[49m[43m,[49m[43m [49m[32;43m270.15[39;49m[43m)[49m
[32m      2[39m [38;5;28mprint[39m([33m'[39m[33mTest 3 Passed![39m[33m'[39m)

[36mFile [39m[32m/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/numpy/testing/_private/utils.py:635[39m, in [36massert_almost_equal[39m[34m(actual, desired, decimal, err_msg, verbose)[39m
[32m    633[39m     [38;5;28;01mpass[39;00m
[32m    634[39m [38;5;28;01mif[39;00m [38;5;28mabs[39m(desired - actual) >= np.float64([32m1.5[39m * [32m10.0[39m**(-decimal)):
[32m--> [39m[32m635[39m     [38;5;28;01mraise[39;00m [38;5;167;01mAssertionError[39;00m(_build_err_msg())

[31mAssertionError[39m: 
Arrays are not almost equal to 7 decimals
 ACTUAL: 273.15
 DESIRED: 270.15

